//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoExpress.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IDOrder { get; set; }
        public int IDCustomer { get; set; }
        public int IDFlight { get; set; }
        public int IDAircraft { get; set; }
        public int IDAirport { get; set; }
        public int IDRoute { get; set; }
        public int IDCargo { get; set; }
        public int IDPayment { get; set; }
        public int IDEmployee { get; set; }
        public int IDStatusOrder { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Route Route { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
    }
}
